import {
  FaHeart,
  FaPen,
  FaTrashAlt,
  FaRegEdit,
  FaTrophy,
  FaBoxOpen,
  FaThumbsUp,
  FaMedal,
  FaRunning,
  FaChartLine,
  FaDumbbell,
  FaFire,
  FaThumbtack,
  FaScroll,
  FaCheckCircle,
  FaNewspaper,
  FaCalendarAlt,
  FaUser,
  FaListUl,
  FaUserGraduate,
  FaTools,
  FaFemale,
  FaBalanceScale,
  FaAppleAlt,
  FaStethoscope,
  FaWheelchair,
} from "react-icons/fa";

export const iconMap = {
  heart: <FaHeart className="text-xl" />,
  pen: <FaPen className="text-xl" />,
  trash: <FaTrashAlt className="text-xl" />,
  edit: <FaRegEdit className="text-xl" />,
  trophy: <FaTrophy className="text-xl" />,
  box: <FaBoxOpen className="text-xl" />,
  thumb: <FaThumbsUp className="text-xl" />,
  medal: <FaMedal className="text-xl" />,
  run: <FaRunning className="text-xl" />,
  chart: <FaChartLine className="text-xl" />,
  dumbbell: <FaDumbbell className="text-xl" />,
  fire: <FaFire className="text-xl" />,
  pin: <FaThumbtack className="text-xl" />,
  scroll: <FaScroll className="text-xl" />,
  check: <FaCheckCircle className="text-xl text-green-500" />,
  news: <FaNewspaper className="text-xl" />,
  calendar: <FaCalendarAlt className="text-xl" />,
  user: <FaUser className="text-xl" />,
  list: <FaListUl className="text-xl" />,
  graduate: <FaUserGraduate className="text-2xl" />,
  tools: <FaTools className="text-2xl" />,
  female: <FaFemale className="text-2xl" />,
  balance: <FaBalanceScale className="text-2xl" />,
  apple: <FaAppleAlt className="text-2xl" />,
  stethoscope: <FaStethoscope className="text-2xl" />,
  wheelchair: <FaWheelchair className="text-2xl" />,
};
